// <auto-generated />
using System;
using DocumentAccessApprovalSystem.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocumentAccessApprovalSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250711192805_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("DocumentAccessApprovalSystem.Domain.AccessRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestedAccessType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AccessRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 0, 0, 0, DateTimeKind.Utc),
                            DocumentId = 1,
                            Reason = "Need for work",
                            RequestedAccessType = 0,
                            Status = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 5, 0, 0, DateTimeKind.Utc),
                            DocumentId = 2,
                            Reason = "Data analysis",
                            RequestedAccessType = 1,
                            Status = 0,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("DocumentAccessApprovalSystem.Domain.Decision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApproverId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccessRequestId")
                        .IsUnique();

                    b.ToTable("Decisions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessRequestId = 1,
                            ApproverId = 2,
                            Comment = "Approved",
                            DecidedAt = new DateTime(2024, 7, 11, 21, 0, 0, 0, DateTimeKind.Utc),
                            IsApproved = true
                        },
                        new
                        {
                            Id = 2,
                            AccessRequestId = 2,
                            ApproverId = 2,
                            Comment = "No permission",
                            DecidedAt = new DateTime(2024, 7, 11, 21, 5, 0, 0, DateTimeKind.Utc),
                            IsApproved = false
                        });
                });

            modelBuilder.Entity("DocumentAccessApprovalSystem.Domain.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Classification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Documents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Classification = "Internal",
                            Description = "Project specification",
                            Name = "Specification"
                        },
                        new
                        {
                            Id = 2,
                            Classification = "Confidential",
                            Description = "Quarterly report",
                            Name = "Report"
                        });
                });

            modelBuilder.Entity("DocumentAccessApprovalSystem.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Role = "User",
                            UserName = "user1"
                        },
                        new
                        {
                            Id = 2,
                            Role = "Approver",
                            UserName = "approver1"
                        });
                });

            modelBuilder.Entity("DocumentAccessApprovalSystem.Domain.Decision", b =>
                {
                    b.HasOne("DocumentAccessApprovalSystem.Domain.AccessRequest", null)
                        .WithOne("Decision")
                        .HasForeignKey("DocumentAccessApprovalSystem.Domain.Decision", "AccessRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocumentAccessApprovalSystem.Domain.AccessRequest", b =>
                {
                    b.Navigation("Decision");
                });
#pragma warning restore 612, 618
        }
    }
}
